# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Mixed Model Equation
#' 
#' @description Solves a univariate mixed model of form \eqn{y=X\beta+Zu+e}.
#'
#' @param y a matrix with n rows and 1 column.
#' @param X a matrix with n rows and x columns.
#' @param Z a matrix with n rows and m columns.
#' @param K a matrix with m rows and m columns.
#' 
#' @examples
#' ## Not to run ##
#' 
#' ## MME(Y, X, Z, K)
#'
#' ## End(Not run)
#' 
#' @useDynLib ezCV
#' 
#' @export MME
MME <- function(y, X, Z, K) {
    .Call('_ezCV_MME', PACKAGE = 'ezCV', y, X, Z, K)
}

#' @title Cross-Validation Without Doing Cross-Validation
#' 
#' @description Performs a Leave-One-Out Cross-Validation Without Doing Cross-Validation using a relationship matrix.
#'
#' @param y is a phenotypic matrix with n rows and 1 column.
#' @param K is a relationship matrix with m rows and m columns.
#' @param lambda is the ratio bwtween residual and genetic variance.
#' @param g is the BLUP solution for the genetic values.
#' 
#' @examples
#' ## Not to run ##
#' 
#' ## LOOCV_DG(Y, G, lambda)
#'
#' ## End(Not run)
#' 
#' @useDynLib ezCV
#'  
#' @export LOOCV_DG
LOOCV_DG <- function(y, K, lambda, g) {
    .Call('_ezCV_LOOCV_DG', PACKAGE = 'ezCV', y, K, lambda, g)
}

#' @title K-folds Cross-Validation Without Doing Cross-Validation
#' 
#' @description Performs a K-folds Cross-Validation Without Doing Cross-Validation using a relationship matrix.
#'
#' @param Y is a phenotypic matrix with n rows and 1 column.
#' @param K is a relationship matrix with m rows and m columns.
#' @param lambda is the ratio bwtween residual and genetic variance.
#' @param folds is a vector with validation sets used to perform k-folds cross-validation.
#' @param g is the BLUP solution for the genetic values.
#' 
#' @examples
#' ## Not to run ##
#' 
#' ## kCV_DG(Y, K, lambda, folds)
#'
#' ## End(Not run)
#' 
#' @useDynLib ezCV
#'  
#' @export kCV_DG
kCV_DG <- function(Y, K, lambda, folds, g) {
    .Call('_ezCV_kCV_DG', PACKAGE = 'ezCV', Y, K, lambda, folds, g)
}

#' @title Ridge Regression BLUP
#'
#' @description Solves a univariate mixed model of form \eqn{y=X\beta+Mu+e}
#'
#' @param y a matrix with n rows and 1 column
#' @param X a matrix with n rows and x columns
#' @param M a matrix with n rows and m columns
#' 
#' @examples
#' ## Not to run ##
#' 
#' ## RRBLUP(y, X, M)
#'
#' ## End(Not run)
#' 
#' @useDynLib ezCV
#' 
#' @export RRBLUP
RRBLUP <- function(y, X, M) {
    .Call('_ezCV_RRBLUP', PACKAGE = 'ezCV', y, X, M)
}

#' @title rrBLUP Cross-Validation Without Doing Cross-Validation
#' 
#' @description Performs a Leave-One-Out Cross-Validation Without Doing Cross-Validation using a relationship matrix.
#'
#' @param Y is a phenotypic matrix with n rows and 1 column.
#' @param X is a matrix with markers in columns and animals in rows.
#' @param B is matrix with markers effect.
#' @param lambda is the ratio bwtween residual and genetic variance.
#' 
#' @examples
#' ## Not to run ##
#' 
#' ## LOOrrDG(Y, X, B, lambda)
#'
#' ## End(Not run)
#' 
#' @useDynLib ezCV
#'  
#' @export LOOrrDG
LOOrrDG <- function(Y, X, B, lambda) {
    .Call('_ezCV_LOOrrDG', PACKAGE = 'ezCV', Y, X, B, lambda)
}

#' @title Cross-Validation Without Doing Cross-Validation on Gibbs Sampling
#' 
#' @description Performs a Leave-One-Out Cross-Validation Without Doing Cross-Validation using Gibbs Sampling results.
#'
#' @param Y is a phenotypic matrix with n rows and 1 column.
#' @param B is a matrix with the posterior distribution of markers effect.
#' @param X is a matrix with markers in columns and animals in rows.
#' @param varE is a vector with the posterior distribution of residual variance.
#' 
#' @examples
#' ## Not to run ##
#' 
#' ## cvBayes(Y=y, B=Effect, X=X, varE=BA_varE)
#'
#' ## End(Not run)
#' 
#' @useDynLib ezCV
#'  
#' @export cvBayes
cvBayes <- function(Y, B, X, varE) {
    .Call('_ezCV_cvBayes', PACKAGE = 'ezCV', Y, B, X, varE)
}

